import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ConvexClerkProvider from "./providers/ConvexClerkProvider";
import { Toaster } from "sonner";
import { ModalProvider } from "./providers/modalProvider";
import { Suspense } from "react";
import { Loading } from "@/components/auth/loading";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Suspense fallback={<Loading/>}>
        <ConvexClerkProvider>
        <Toaster/>
        <ModalProvider/>
        {children}
        </ConvexClerkProvider>
        </Suspense>
      </body>
    </html>
  );
}
